### ISSUE TITLE
iPhone16系列设备使用系统相机录制的视频 使用该类导出失败

### ISSUE THREAD

**Issue by litianying137** [rs/SDAVAssetExportSession#104]

**Comment by litianying137** [comment]
更新读取音频outputSetting 新增 [NSNumber numberWithFloat:2], AVNumberOfChannelsKey 属性
NSDictionary *outputSettings = [NSDictionary dictionaryWithObjectsAndKeys:
                                            [NSNumber numberWithInt:kAudioFormatLinearPCM], AVFormatIDKey,
                                            [NSNumber numberWithFloat:44100.0], AVSampleRateKey,
                                            [NSNumber numberWithFloat:2], AVNumberOfChannelsKey,
                                            [NSNumber numberWithInt:16], AVLinearPCMBitDepthKey,
                                            [NSNumber numberWithBool:NO], AVLinearPCMIsNonInterleaved,
                                            [NSNumber numberWithBool:NO], AVLinearPCMIsFloatKey,
                                            [NSNumber numberWithBool:NO], AVLinearPCMIsBigEndianKey,
                                            nil];

**Comment by buvtopcc** [comment]
Finally how to do, I see the source code AVNumberOfChannelsKey parameter is set to 2, but in the iPhone16 export failure

**Comment by LaurelYu** [comment]
> 最后怎么办呢，我看源代码中AVNumberOfChannelsKey参数设置为2，但是在iPhone16上导出失败

你好，最后怎么解决的啊？@buvtopcc

**Comment by buvtopcc** [comment]
using system AVAssetExportSession to replace the SDAVAssetExportSession.

**Comment by hafiz-mohsin-confiz** [comment]
Hi @LaurelYu ,@buvtopcc
I have fixed the issue reported by @litianying137 videos being captured from main Camera using iPhone 16 Pro or Pro Max devices cause the encoding failure using the below code changes in this encoding class.

#define kAudioFormatAPAC 'apac' // Apple Pro Audio Codec //This Enum is available in Xcode 16 by apple, however if you are in lower version of Xcode then you can use the above mention custom declaration of enum in the class.

Reference Link: https://github.com/xamarin/xamarin-macios/wiki/CoreAudioTypes-iOS-xcode16.0-b3
Issue being reported by another Open Source Library for iPhone 16 Pro and Pro Max device
https://github.com/NextLevel/NextLevelSessionExporter/issues/49
    
Solution:
   
    NSArray *audioTracks = [self.asset tracksWithMediaType:AVMediaTypeAudio];
    
    NSMutableArray<AVAssetTrack *> *audioTracksToUse = [NSMutableArray array];

    // Iterate through audioTracks
    for (AVAssetTrack *audioTrack in audioTracks) {
        NSArray *formatDescriptions = audioTrack.formatDescriptions;
        for (id formatDescription in formatDescriptions) {
            if (CMFormatDescriptionGetMediaType((CMFormatDescriptionRef)formatDescription) == kCMMediaType_Audio) {
                FourCharCode mediaSubtype = CMFormatDescriptionGetMediaSubType((CMFormatDescriptionRef)formatDescription);
                if (mediaSubtype != kAudioFormatAPAC) {
                    [audioTracksToUse addObject:audioTrack];
                    break; // Prevent adding the same track multiple times
                }
            }
        }
    }

   if (audioTracks.count > 0) {
        self.audioOutput = [AVAssetReaderAudioMixOutput assetReaderAudioMixOutputWithAudioTracks:audioTracksToUse audioSettings:nil];
        self.audioOutput.alwaysCopiesSampleData = NO;
        self.audioOutput.audioMix = self.audioMix;
        if ([self.reader canAddOutput:self.audioOutput])
        {
            [self.reader addOutput:self.audioOutput];
        }
    } else {
        // Just in case this gets reused
        self.audioOutput = nil;
    }

**Comment by buvtopcc** [comment]
Does the code fit in？@hafiz-mohsin-confiz

**Comment by hafiz-mohsin-confiz** [comment]
Hi @buvtopcc ,
Yes, and it's working fine now.

**Comment by buvtopcc** [comment]
OK，Can you post the PR link that you have entered? @hafiz-mohsin-confiz
