### ISSUE TITLE
ERROR *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVAssetReaderVideoCompositionOutput initWithVideoTracks:videoSettings:] invalid parameter not satisfying: [videoTracks count] >= 1'

### ISSUE THREAD

**Issue by kohdesmond** [rs/SDAVAssetExportSession#4]
Hi There,

i encountered an error, i hope you will be able to tell me what's going wrong.

thanks 

Des

- (void)mediaPicker:(MPMediaPickerController *)mediaPicker didPickMediaItems:(MPMediaItemCollection *)mediaItemCollection {
    
    [self dismissViewControllerAnimated:YES completion:nil];
    
    for (MPMediaItem* item in mediaItemCollection.items)
    {   
		NSString* title = [item valueForProperty:MPMediaItemPropertyTitle];
		self.assetURL = [item valueForProperty:MPMediaItemPropertyAssetURL];
        NSString* albumTitle = [item valueForProperty:MPMediaItemPropertyAlbumTitle];
        NSString* artist = [item valueForProperty:MPMediaItemPropertyArtist];
        NSString* genre = [item valueForProperty:MPMediaItemPropertyGenre];
        NSLog(@"title: %@, url: %@ %@ %@ %@", title, self.assetURL,albumTitle,artist,genre);
    }
    
    self.asset = [AVAsset assetWithURL:self.assetURL];
    
    // Path of your destination save audio file
    
    NSArray *paths = NSSearchPathForDirectoriesInDomains( NSDocumentDirectory, NSUserDomainMask ,YES );
    NSString *documentsDir = [paths objectAtIndex:0];
    NSString *savedPath = [documentsDir stringByAppendingPathComponent:[NSString stringWithFormat:@"audio.m4a"]];
    
    NSLog(@"cacheDir %@",savedPath);
    [self exportTrimAudio11:self.asset toFilePath:savedPath];

}
- (BOOL)exportTrimAudio11:(AVAsset *)avAsset toFilePath:(NSString *)filePath
{
    // we need the audio asset to be at least 50 seconds long for this snippet
    CMTime assetTime = [avAsset duration];
    Float64 duration = CMTimeGetSeconds(assetTime);
    if (duration < 50.0) return NO;
    // create trim time range - 30 seconds starting from 10 seconds into the asset
    CMTime startTime = CMTimeMake(10, 1);
    CMTime stopTime = CMTimeMake(40, 1);
    CMTimeRange exportTimeRange = CMTimeRangeFromTimeToTime(startTime, stopTime);
    SDAVAssetExportSession *encoder = [[SDAVAssetExportSession alloc] initWithAsset:avAsset];
    encoder.outputFileType = AVFileTypeAppleM4A;
    encoder.outputURL=[NSURL fileURLWithPath:filePath];
    encoder.timeRange = exportTimeRange;
    //encoder.shouldOptimizeForNetworkUse = YES;
    encoder.audioSettings = @
    {
    AVFormatIDKey: @(kAudioFormatMPEG4AAC),
    AVNumberOfChannelsKey: @2,
    AVSampleRateKey: @44100,
    AVEncoderBitRateKey: @128000,
    };
    
    // perform the export
    [encoder exportAsynchronouslyWithCompletionHandler:^{
        
        if (AVAssetExportSessionStatusCompleted == encoder.status) {
            NSLog(@"AVAssetExportSessionStatusCompleted");
        } else if (AVAssetExportSessionStatusFailed == encoder.status) {
            // a failure may happen because of an event out of your control
            // for example, an interruption like a phone call comming in
            // make sure and handle this case appropriately
            NSLog(@"AVAssetExportSessionStatusFailed");
        } else {
            NSLog(@"Export Session Status: %d", encoder.status);
            
        }
    }];
    
    return YES;
}

**Comment by hakanw** [comment]
https://github.com/rs/SDAVAssetExportSession/pull/25 will fix this
