### ISSUE TITLE
Bad video cropping

### ISSUE THREAD

**Issue by thibauddavid** [rs/SDAVAssetExportSession#47]
Hi,

When trying to re-encode a MOV to MP4 with example from readme, I get borders on left and right with rear camera device, and a square crop with front camera.

Without any re-encoding, my player (PBJVideoPlayerController, using AVLayerVideoGravityResizeAspectFill) displays correctly the fullscreen video.

I guess there is something wrong with renderSize of SDAVAssetExportSession, but I don't really understand why nobody else seems to have the problem.

Here are screenshots with front and rear camera after re-encoding :

Screenshot of video without re-encoding, rear camera: http://imgur.com/SyoQcDF (perfectly fullscreen)
Screenshot of video with re-encoding, rear camera : http://imgur.com/DLFbAeW
Screenshot of video with re-encoding, front camera : http://imgur.com/8WelhWF

As you can see, the player shouldn't be the problem as everything is ok without re encoding. But after exporting, borders appears with rear, and I-don't-know-really-know-what-happens with front camera...

Any help ?

Thanks a lot !

PS : Like my coffee bowl ?

Edit : Cloned this to stackoverflow( http://stackoverflow.com/questions/33957150/strange-cropping-behaviour ), I will update both pages according to answers

**Comment by rossmartin** [comment]
I also have the same issue.  I've tried every possible value for the `AVVideoScalingModeKey` (AVVideoScalingModeFit, AVVideoScalingModeResize, AVVideoScalingModeResizeAspect, & AVVideoScalingModeResizeAspectFill).


```
    encoder.videoSettings = @
    {
        AVVideoCodecKey: AVVideoCodecH264,
        AVVideoWidthKey: @1920,
        AVVideoHeightKey: @1080,
        AVVideoScalingModeKey: AVVideoScalingModeResizeAspectFill, // <-- this doesn't fix it surprisingly
        AVVideoCompressionPropertiesKey: @
        {
            AVVideoAverageBitRateKey: @6000000,
            AVVideoProfileLevelKey: AVVideoProfileLevelH264High40
        }
    };
```

**Comment by rossmartin** [comment]
I've realized that bad video cropping will occur if you give a portrait video more width than height and deviate from the aspect ratio that it needs.  The same will occur for a landscape video if you give it more height than width.

My solution is to get the videos aspect ratio and current dimensions first before transcoding and then calculate a smaller width and height based off its current dimensions in order to maintain the aspect ratio.  This will keep the resulting video from having black borders.

**Comment by rossmartin** [comment]
@Tibabal here is some code that shows how to resize and keep  the aspect ratio and avoid cropping issues.  Note that the `width` and `height` are integer variables controlled by the user.  If they aren't provided I transcode with the original video width and height.

```objective-c
AVURLAsset *avAsset = [AVURLAsset URLAssetWithURL:[NSURL fileURLWithPath:assetPath] options:nil];

NSString *cacheDir = [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) objectAtIndex:0];
NSString *outputPath = [NSString stringWithFormat:@"%@/%@%@", cacheDir, videoFileName, outputExtension];
NSURL *outputURL = [NSURL fileURLWithPath:outputPath];

NSArray *tracks = [avAsset tracksWithMediaType:AVMediaTypeVideo];
AVAssetTrack *track = [tracks objectAtIndex:0];
CGSize mediaSize = track.naturalSize;

float videoWidth = mediaSize.width;
float videoHeight = mediaSize.height;
float aspectRatio = videoWidth / videoHeight;
int newWidth = (width && height) ? height * aspectRatio : videoWidth;
int newHeight = (width && height) ? newWidth / aspectRatio : videoHeight;

NSLog(@"input videoWidth: %f", videoWidth);
NSLog(@"input videoHeight: %f", videoHeight);
NSLog(@"output newWidth: %d", newWidth);
NSLog(@"output newHeight: %d", newHeight);

SDAVAssetExportSession *encoder = [SDAVAssetExportSession.alloc initWithAsset:avAsset];
encoder.outputFileType = stringOutputFileType;
encoder.outputURL = outputURL;
encoder.videoSettings = @
{
    AVVideoCodecKey: AVVideoCodecH264,
    AVVideoWidthKey: [NSNumber numberWithInt: newWidth],
    AVVideoHeightKey: [NSNumber numberWithInt: newHeight],
    AVVideoCompressionPropertiesKey: @
    {
        AVVideoAverageBitRateKey: [NSNumber numberWithInt: videoBitRate],
        AVVideoProfileLevelKey: AVVideoProfileLevelH264High40
    },
};
encoder.audioSettings = @
{
    AVFormatIDKey: @(kAudioFormatMPEG4AAC),
    AVNumberOfChannelsKey: [NSNumber numberWithInt: audioChannels],
    AVSampleRateKey: [NSNumber numberWithInt: audioSampleRate],
    AVEncoderBitRateKey: [NSNumber numberWithInt: audioBitRate],
};

[encoder exportAsynchronouslyWithCompletionHandler:^
{
    if (encoder.status == AVAssetExportSessionStatusCompleted)
    {
        NSLog(@"Video export succeeded");
        [self.commandDelegate sendPluginResult:[CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:outputPath] callbackId:command.callbackId];
    }
    else if (encoder.status == AVAssetExportSessionStatusCancelled)
    {
        NSLog(@"Video export cancelled");
        [self.commandDelegate sendPluginResult:[CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Video export cancelled"] callbackId:command.callbackId];
    }
    else
    {
        NSString *error = [NSString stringWithFormat:@"Video export failed with error: %@ (%ld)", encoder.error.localizedDescription, (long)encoder.error.code];
        NSLog(error);
        [self.commandDelegate sendPluginResult:[CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:error] callbackId:command.callbackId];
    }
}];

```

**Comment by Tibabal** [comment]
Thanks @rossmartin , I'll try this if I have a later need of this functionality

**Comment by kylebrowning** [comment]
This is still happening for me for front facing camera uploads.
