### ISSUE TITLE
Set framerate of exported video

### ISSUE THREAD

**Issue by awidgery** [rs/SDAVAssetExportSession#52]
I have a 240fps 720p video recorded on the iPhone's internal camera which I'm trying to compress while maintaining the frame rate and resolution:

```
SDAVAssetExportSession *exportSession = [[SDAVAssetExportSession alloc] initWithAsset:asset];

exportSession.videoSettings =
@{
  AVVideoCodecKey: AVVideoCodecH264,
  AVVideoWidthKey: @1280,
  AVVideoHeightKey: @720,
  AVVideoCompressionPropertiesKey: @
      {
      AVVideoAverageBitRateKey: @1100000,
      AVVideoProfileLevelKey: AVVideoProfileLevelH264High40,
      },
  };

exportSession.audioSettings = @
{
AVFormatIDKey: @(kAudioFormatMPEG4AAC),
AVNumberOfChannelsKey: @2,
AVSampleRateKey: @44100,
AVEncoderBitRateKey: @128000,
};
```

This works, but the video is outputted as a 30fps file. Can I get SDAVAssetExportSession to output at 240fps (or just to keep the same framerate as input)?

**Comment by gsabran** [comment]
You can add an entry for `AVVideoMaxKeyFrameIntervalKey` see: https://github.com/rs/SDAVAssetExportSession/blob/master/SDAVAssetExportSession.m#L291-L295.

ie: 

```Objective C
exportSession.videoSettings =
@{
  AVVideoCodecKey: AVVideoCodecH264,
  AVVideoWidthKey: @1280,
  AVVideoHeightKey: @720,
  AVVideoCompressionPropertiesKey: @
      {
      AVVideoAverageBitRateKey: @1100000,
      AVVideoProfileLevelKey: AVVideoProfileLevelH264High40,
      AVVideoMaxKeyFrameIntervalKey: 240,
      },
  };

```

That being said, it is defaulting to the video frame rate if possible before falling back to 30fps: https://github.com/rs/SDAVAssetExportSession/blob/master/SDAVAssetExportSession.m#L298-L301
Are you sure you're recording at 240fps?

**Comment by gstream** [comment]
@rs , I've tried to set `AVVideoMaxKeyFrameIntervalKey` but fps is not changed. Exported video's fps is 43.33 fps for 240fps slow motion even I set `AVVideoMaxKeyFrameIntervalKey: @240`
Any idea how to fix this issue ?
