### ISSUE TITLE
Quality-based compression?

### ISSUE THREAD

**Issue by awidgery** [rs/SDAVAssetExportSession#55]
I am compressing a video for upload using SDAVAssetExportSession:

```
SDAVAssetExportSession *exportSession = [[SDAVAssetExportSession alloc] initWithAsset:composition];

exportSession.videoSettings =
@{
  AVVideoCodecKey: AVVideoCodecH264,
  AVVideoWidthKey: @640,
  AVVideoHeightKey: @640,
  AVVideoCompressionPropertiesKey: @
      {
      AVVideoAverageBitRateKey: @1100000,
      AVVideoProfileLevelKey: AVVideoProfileLevelH264High40,
      },
  };
```

When encoding video using [Handbrake](https://handbrake.fr/) on OSX I can choose to use a "Constant Quality" setting instead of average bitrate:

[![enter image description here](http://i.stack.imgur.com/w95Aa.png)](http://i.stack.imgur.com/w95Aa.png)

This seems to give better results on a variety of video sources.

Can I do the same with `SDAVAssetExportSession`?

If not, is there another way I could compress the video using "Constant Quality" compression?

(post referred from http://stackoverflow.com/questions/36864682/sdavexportsession-quality-based-compression)

**Comment by gsabran** [comment]
I think you can provide a value for `AVVideoQualityKey` in `AVVideoCompressionPropertiesKey` since it's gonna be passed here: https://github.com/rs/SDAVAssetExportSession/blob/master/SDAVAssetExportSession.m#L108
