### ISSUE TITLE
Issue with portrait video

### ISSUE THREAD

**Issue by TheSquad** [rs/SDAVAssetExportSession#6]
Hi, First of all thank you for your work, it is a great drop-in replacement !

Compressing Landscape video works great, fast, and painless...
However Portrait video does not seems to be as painless ;-)

I'm having issue with result video being strechted, but more than a thousand words here the original and result screens...

Original
![720x1280](https://f.cloud.github.com/assets/1867508/1556127/b8d3ff18-4eaf-11e3-921b-a67e3c93f946.jpg)

Result
![result](https://f.cloud.github.com/assets/1867508/1556129/cdab66f6-4eaf-11e3-9f48-4b3f5ec21f9d.png)

Has you can see, is it streched down on the width, and streched up on the height... I cannot seems to find out why...

My code using your class is : 

```
    AVAsset *asset = [AVAsset assetWithURL:[info objectForKey:@"UIImagePickerControllerMediaURL"]];
    AVAssetTrack *videoTrack = [[asset tracksWithMediaType:AVMediaTypeVideo] objectAtIndex:0];

    CGSize renderSize = [PMVideoTools getVideoSize:asset]; // Aware of orientation

    NSLog(@"Transfer RenderSize %f - %f", renderSize.width, renderSize.height);

    SDAVAssetExportSession *encoder = [SDAVAssetExportSession.alloc initWithAsset:asset];
    encoder.outputFileType = AVFileTypeMPEG4;
    encoder.outputURL = [PMVideoTools createURLWithFileName:@"output.mp4"];

    NSLog(@"Exporting to : %@", encoder.outputURL.path);
    encoder.videoSettings = @
    {
    AVVideoCodecKey: AVVideoCodecH264,
    AVVideoWidthKey: [NSNumber numberWithFloat:(renderSize.width)],
    AVVideoHeightKey: [NSNumber numberWithFloat:(renderSize.height)],
    AVVideoCompressionPropertiesKey: @
        {
        AVVideoAverageBitRateKey: [NSNumber numberWithInt:videoTrack.estimatedDataRate],
        AVVideoProfileLevelKey: AVVideoProfileLevelH264BaselineAutoLevel,
        },
    };

    encoder.audioSettings = @
    {
        AVFormatIDKey: @(kAudioFormatMPEG4AAC),
        AVNumberOfChannelsKey: @2,
        AVSampleRateKey: @44100,
        AVEncoderBitRateKey: @128000,
    };
```

Is there something wrong with my code ?

**Comment by GabeRoze** [comment]
I also have this issue and had to copy @TheSquad 's code. I can try submitting a pull request it if I get a chance
