### ISSUE TITLE
Transform for front facing camera results in half of the video missing

### ISSUE THREAD

**Issue by pnicholls** [rs/SDAVAssetExportSession#68]
I have video that is coming in from the front facing camera with the following properties:

Property | Value
------------ | -------------
natural size width | 1280.000000 
natural size height | 720.000000
target size width | 720.000000
target size height | 1280.000000
preferredTransform | a: 0.000000 b: 1.000000 c: 1.000000 d: 0.000000 tx: 0.000000 ty: 0.000000

Which results in a video missing half of its content:

![simulator screen shot 5 apr 2017 6 58 24 am](https://cloud.githubusercontent.com/assets/139051/24678446/f0293766-19cd-11e7-9db3-be789655d7b4.png)

I would love to fix this myself but I have yet to get a good grasp on how the transforms work. Any tips?

Cheers!

**Comment by sathishvudugundla** [comment]
i also faced the same issue can anyone have any idea

**Comment by pnicholls** [comment]
Fix can be found here https://github.com/rs/SDAVAssetExportSession/pull/70
