### ISSUE TITLE
Export video in background

### ISSUE THREAD

**Issue by Sashom** [rs/SDAVAssetExportSession#8]
Hi, is there a way to make this work (at least in the allowed 3 minutes) in the background in case I hit the home button while export is being made?

**Comment by mikezucc** [comment]
Have the app delegate maintain a strong reference to the SD object?

**Comment by bcattle** [comment]
You do this by calling [`beginBackgroundTaskWithExporationHandler:`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instm/UIApplication/beginBackgroundTaskWithExpirationHandler:), for example:

    if ([[UIDevice currentDevice] isMultitaskingSupported]) {
        self.backgroundRecordingID = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:^{
                // If the task expires, just end it to avoid having the app terminated
                [[UIApplication sharedApplication] endBackgroundTask:self.backgroundRecordingID];
                self.backgroundRecordingID = UIBackgroundTaskInvalid;
                NSLog(@"ERROR: recording background task timed out");
            }];
    }

**Comment by bcattle** [comment]
Eh there should probably be a `weakSelf` in there, but you get the idea
